name: Nightly Build and Analysis

on:
  schedule:
    - cron: "0 0 * * *" # 每天午夜触发

jobs:
  nightly-build-and-analysis:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cppcheck
      run: |
        if [ ${{ runner.os }} == 'Linux' ]; then
          sudo apt-get install -y cppcheck;
        elif [ ${{ runner.os }} == 'Windows' ]; then
          choco install cppcheck;
        fi

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --xml --xml-version=2 src 2> cppcheck-report.xml
        cppcheck --enable=all src

    - name: Upload cppcheck results
      uses: actions/upload-artifact@v3
      with:
        name: cppcheck-report-${{ matrix.os }}
        path: cppcheck-report.xml

    - name: Build project
      run: |
        make clean
        make all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nightly-build-${{ matrix.os }}
        path: hello_world${{ matrix.os == 'windows-latest' && '.exe' || '' }}