name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # 每日UTC时间00:00触发
  workflow_dispatch:     # 允许手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装依赖（Windows）
      if: matrix.os == 'windows-latest'
      run: |
        choco install mingw -y  # 安装Mingw编译器
        choco install cppcheck -y  # 安装静态分析工具

    - name: 安装依赖（Linux）
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck  # 安装静态分析工具

    - name: 静态代码分析
      run: |
        mkdir -p reports
        cppcheck --enable=all --xml-version=2 src/ 2> reports/cppcheck-report-${{ matrix.os }}.xml

    - name: 上传分析报告
      uses: actions/upload-artifact@v3
      with:
        name: cppcheck-reports-${{ matrix.os }}
        path: reports/

    - name: 构建Linux版本
      if: matrix.os == 'ubuntu-latest'
      run: |
        make linux

    - name: 构建Windows版本
      if: matrix.os == 'windows-latest'
      run: |
        make windows

    - name: 发布Nightly版本
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-$(date -u +'%Y%m%d')
        name: Nightly Build $(date -u +'%Y-%m-%d')
        body: "包含静态分析报告的每日构建版本"
        draft: false
        prerelease: true
        files: |
          bin/hello-world.exe
          bin/hello-world